
var module = {
    "module":module,
    "ProductDetail": productDetailCtrl,
    "ProductPageController": productListCtrl,
    "loginSelectBox": loginSelectBoxCtrl,
    "pesonalLogin": personalLoginCtrl,
    "shopLogin": shopLoginCtrl,
    "shopHome":shopHomeCtrl,
    "home": homeCtrl,
    "side": sideCtrl,
    "firstClassfy": firstClassfyCtrl,
    "shoppingCart": shoppingCartCtrl,
    "editCart": editCartCtrl,
    "personalCenter": personalCenterCtrl,
    "updatePassword": updatePasswordCtrl,
    "updatePasswordNext": updatePasswordNextCtrl,
    "shopDetail": shopDetailCtrl,
    "register": registerCtrl,
    "position": positionCtrl,
    "confirmOrder": confirmOrderCtrl,
    "addrEdit": addrEditCtrl,
    "addrList": addrListCtrl,
    "addrNew": addrNewCtrl,
    "order": orderCtrl,
    "xxyl": xxylCtrl,
    "sjtx": sjtxCtrl,
    "jypx": jypxCtrl,
    "jdlg": jdlgCtrl,
    "fzfs": fzfsCtrl,
    "fc": fcCtrl,
    "cyms": cymsCtrl,
    "csdg": csdgCtrl,
    "classfy": classfyCtrl,
    "editClassfy": editClassfyCtrl,
    "search": searchCtrl,
    "shopList": shopListCtrl,
    "changeinformation": changeinformationCtrl,
    "message": messageCtrl,
    "Mycollection": MycollectionCtrl,
    "recentvisit": recentvisitCtrl,
    "set": setCtrl,
    "connect": connectCtrl,
    "about": aboutCtrl,
    "delrecentvisit": delrecentvisitCtrl,
    "feedback":feedbackCtrl,
    "activityMessage":activityMessageCtrl
}